/** @format */
//register
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
//login
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
//admin
//question
export const GET_QUESTION_SUCCESS = "GET_QUESTION_SUCCESS";
export const GET_QUESTION_FAIL = "GET_QUESTION_FAIL";
//user
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

//user
//question
export const USER_GET_QUESTION_SUCCESS ="USER_GET_QUESTION_SUCCESS"
export const USER_GET_QUESTION_FAIL ="USER_GET_QUESTION_FAIL"
//answer
export const USER_SUBMIT_ANSWER_SUCCESS ="USER_SUBMIT_ANSWER_SUCCESS"
export const USER_SUBMIT_ANSWER_FAIL ="USER_SUBMIT_ANSWER_FAIL"
